#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — ADR-0061's one-time human steps for the Linux store channels.
# Secrets the release workflow reads (must match release.yml exactly):
#   GPG_PRIVATE_KEY · SNAPCRAFT_STORE_CREDENTIALS · FLATHUB_SSH_KEY
#   (GPG_PASSPHRASE stays unset — the key has none.)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
REPO="upyesp/epher"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

banner "epher: provision the Linux store channels"

# ── Stage 1 — preflight ───────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard drives."
PREFLIGHT_OK=true
for tool in gh git gpg curl sha256sum ssh-keygen; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s missing' "$RED" "$RESET" "$tool"
    PREFLIGHT_OK=false
  fi
done
if [[ "$PREFLIGHT_OK" == true ]] && gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s gh authenticated as %s\n' "$GREEN" "$RESET" \
    "$(gh api user --jq .login 2>/dev/null || echo '?')"
  printf '  %s✓%s target repo: %s\n' "$GREEN" "$RESET" "$REPO"
else
  warn "gh is missing or not authenticated — secrets cannot be set this run."
  warn "Run: gh auth login   — then re-run this wizard."
fi
RELEASE_TAG=$(gh release view --repo "$REPO" --json tagName -q .tagName 2>/dev/null || echo "v0.5.34")
RELEASE_NUM=${RELEASE_TAG#v}
note "working from release $RELEASE_TAG (the latest)"
pause "Press Enter to continue"

# ── Stage 2 — GPG key for the apt + dnf repositories ─────────────────────
stage "GPG key (apt + dnf signing)"
say "The repositories are signed with one RSA-4096 key, no passphrase."
say "Its private half becomes the GPG_PRIVATE_KEY secret; the public half"
say "is published at epher.org/apt/KEY.gpg by the release job itself."
if gpg --list-secret-keys "release@epher.org" >/dev/null 2>&1; then
  note "a key for release@epher.org already exists — reusing it."
else
  step "Generating the key (local, no browser)."
  gpg --batch --passphrase '' --quick-gen-key \
    "epher release <release@epher.org>" rsa4096 sign 0
fi
GPG_FPR=$(gpg --list-secret-keys --with-colons "release@epher.org" \
  | awk -F: '/^fpr/{print $10; exit}')
note "fingerprint: $GPG_FPR"
if confirm "Set GPG_PRIVATE_KEY from this key?"; then
  gpg --armor --export-secret-keys "$GPG_FPR" \
    | gh secret set GPG_PRIVATE_KEY --repo "$REPO"
  WRITTEN_SECRET+=("GPG_PRIVATE_KEY")
  printf '  %s✓ set%s GitHub secret GPG_PRIVATE_KEY\n' "$GREEN" "$RESET"
  say "The NEXT release builds and smoke-tests both repositories."
  say "(Optional: publish the pubkey to a keyserver —"
  say "  gpg --send-keys $GPG_FPR )"
fi
pause "Press Enter to continue"

# ── Stage 3 — Snap Store ─────────────────────────────────────────────────
stage "Snap Store (snap install epher)"
if confirm "Configure the Snap Store secret now? (Enter/N skips if already done)"; then
  say "Two ways to finish this stage:"
  say ""
  say "  A. RECOMMENDED — on another machine with snapcraft (Windows +"
  say "     WSL2, Linux Mint, …): snapcraft login; snapcraft register epher;"
  say "     snapcraft export-login --snaps=epher creds.txt; then paste the"
  say "     file's content below when asked."
  say ""
  say "  B. Dispatch the runner workflow here — the device URL prints in"
  say "     its run log."
  if confirm "Already exported credentials on another machine? Paste them now"; then
    say "Paste the exported credentials file content, then press Ctrl-D:"
    CREDS=$(cat || true)
    if [[ -n "$CREDS" ]]; then
      set_secret SNAPCRAFT_STORE_CREDENTIALS "$CREDS"
    else
      warn "nothing pasted — stage skipped; re-run me later."
      SKIPPED+=("Snap Store (nothing pasted)")
    fi
  else
    say "Dispatching the snap-store-login workflow…"
    gh workflow run snap-store-login.yml --repo "$REPO" -f snap_name=epher
    sleep 6
    WORK=$(mktemp -d)
    RUN_ID=$(gh run list --repo "$REPO" --workflow snap-store-login.yml \
      --limit 1 --json databaseId --jq '.[0].databaseId')
    note "run: https://github.com/$REPO/actions/runs/$RUN_ID"
    say "Waiting for the device URL…"
    URL_SHOWN=false
    STATUS=""
    while :; do
      STATUS=$(gh run view "$RUN_ID" --repo "$REPO" --json status,conclusion \
        --jq '.status + " " + (.conclusion // "")')
      if [[ "$URL_SHOWN" == false ]]; then
        OUTPUT=$(gh run view "$RUN_ID" --repo "$REPO" --log 2>/dev/null \
          | grep "Log in, register, and export" \
          | sed -E 's/^[^\t]*\t[^\t]*\t[0-9TZ:.\-]+ //' \
          | grep -vE "^##\[|^shell:|^env:|SNAPCRAFT_STORE_AUTH|command -v" || true)
        if printf '%s' "$OUTPUT" | grep -qi "login.ubuntu.com\|code"; then
          printf '%s\n' "$OUTPUT" | sed 's/^/  │ /'
          URL_SHOWN=true
          say "Open the login.ubuntu.com URL above on any device and enter the code."
        fi
      fi
      [[ "$STATUS" == completed* ]] && break
      sleep 8
    done
    if [[ "$STATUS" != *success* ]]; then
      warn "The login run did not succeed ($STATUS). Check:"
      warn "  https://github.com/$REPO/actions/runs/$RUN_ID"
      exit 1
    fi
    step "Downloading the exported CI credentials."
    gh run download "$RUN_ID" --repo "$REPO" -n snap-store-credentials -D "$WORK"
    if confirm "Set SNAPCRAFT_STORE_CREDENTIALS from the exported key?"; then
      set_secret SNAPCRAFT_STORE_CREDENTIALS "$(cat "$WORK/snap-store-credentials")"
    fi
    rm -rf "$WORK"
    ART_ID=$(gh api "repos/$REPO/actions/artifacts" \
      --jq '.artifacts[] | select(.name=="snap-store-credentials") | .id' | head -1)
    [[ -n "$ART_ID" ]] && gh api -X DELETE "repos/$REPO/actions/artifacts/$ART_ID" \
      >/dev/null 2>&1 && note "credentials artifact deleted from the run."
  fi
else
  note "Skipping — SNAPCRAFT_STORE_CREDENTIALS stays as it is."
  SKIPPED+=("Snap Store (kept existing credentials)")
fi
pause "Press Enter to continue"

# ── Stage 4 — Flathub submission ─────────────────────────────────────────
stage "Flathub submission (PR — human review, days)"
say "The manifest rides a PR to flathub/flathub. New applications target"
say "their 'new-pr' branch — a PR against master gets closed by their"
say "bots (that is what happened to #10095). Their maintainers review,"
say "then create github.com/flathub/com.epher.Desktop for you."
step "Forking flathub/flathub (idempotent)."
gh repo fork flathub/flathub --clone=false || true
FORK=$(gh api "user" --jq .login)
FLAT=$(mktemp -d)
gh repo clone "$FORK/flathub" "$FLAT" -- --depth 1
(
  cd "$FLAT"
  # Branch from upstream's new-pr, NOT master: flathub's new-pr branch
  # shares no history with master, and a PR from a master-based branch
  # is rejected ("no history in common").
  git fetch --depth=1 upstream new-pr
  git switch -C epher FETCH_HEAD
  mkdir -p com.epher.Desktop
  cp "$REPO_ROOT/packaging/flatpak/com.epher.Desktop.yml" com.epher.Desktop/
  cp "$REPO_ROOT/packaging/flatpak/com.epher.Desktop.desktop" com.epher.Desktop/
  cp "$REPO_ROOT/packaging/flatpak/com.epher.Desktop.metainfo.xml" com.epher.Desktop/
  cp "$REPO_ROOT/site/icon.svg" com.epher.Desktop/com.epher.Desktop.svg
  # The manifest references its siblings one directory up in this repo.
  sed -i 's|path: packaging/flatpak/|path: |' com.epher.Desktop/com.epher.Desktop.yml
  sed -i 's|path: site/icon.svg|path: com.epher.Desktop.svg|' com.epher.Desktop/com.epher.Desktop.yml
  git add -A
  git diff --cached --quiet || git commit -qm "epher: add com.epher.Desktop"
  git push -f origin epher
)
EXISTING=$(gh pr list --repo flathub/flathub --head "$FORK:epher" \
  --state open --json number --jq '.[0].number' 2>/dev/null || true)
if [[ -n "$EXISTING" ]]; then
  note "PR #$EXISTING already exists — not creating a duplicate."
  PR_URL="https://github.com/flathub/flathub/pull/$EXISTING"
else
  step "Opening the submission PR against new-pr."
  PR_URL=$(gh pr create --repo flathub/flathub \
    --base new-pr \
    --head "$FORK:epher" \
    --title "epher: add com.epher.Desktop" \
    --body "Initial submission for epher $RELEASE_NUM — a programmable, scriptable calculator (MIT). Manifest, desktop file, and AppStream metainfo included. Home: https://epher.org" 2>/dev/null \
    || echo "https://github.com/flathub/flathub/pulls")
fi
open_url "$PR_URL"
say "The review takes days. When accepted, Flathub creates"
say "github.com/flathub/com.epher.Desktop and adds you as maintainer —"
say "then come back and run Stage 5."
pause "Press Enter to continue"

# ── Stage 5 — Flathub deploy key (after acceptance) ──────────────────────
stage "Flathub deploy key (after acceptance)"
if gh repo view flathub/com.epher.Desktop >/dev/null 2>&1; then
  say "The Flathub repository exists — adding a read-write deploy key."
  FLAT_KEY=$(mktemp)
  ssh-keygen -t ed25519 -N "" -C "epher-flathub-ci" -f "$FLAT_KEY" -q
  gh api -X POST "repos/flathub/com.epher.Desktop/keys" \
    -f title="epher release bot" \
    -f key="$(cat "$FLAT_KEY.pub")" \
    -F read_only=false >/dev/null
  if confirm "Set FLATHUB_SSH_KEY from the new private key?"; then
    set_secret FLATHUB_SSH_KEY "$(cat "$FLAT_KEY")"
  fi
  rm -f "$FLAT_KEY" "$FLAT_KEY.pub"
  note "From the next release on, store-bumps commits version bumps and"
  note "Flathub's bot builds them — no human step left."
else
  warn "github.com/flathub/com.epher.Desktop does not exist yet."
  warn "Come back after the submission PR is accepted, then re-run this"
  warn "wizard (or just this stage) to finish."
fi

finish
