#!/usr/bin/env python3
"""Sync the shared editor assets into the Visual Studio extension.

Two conversions, both committed here and regenerated by this script
(never edit the generated files):

- the grammar ships as plist XML (`Grammars/epher.tmLanguage`): the
  Visual Studio TextMate engine reads the plist form, like the
  JetBrains and Sublime clients. Unlike those clients, the VSIX copy
  must declare `fileTypes`: the editor's TextMate repository matches
  files by the grammar's declared extensions, where VS Code normally
  takes that mapping from its own manifest. So the JSON's truth gains
  one field here, `fileTypes: ["epher"]`, and nothing else.
- the language configuration (`epher-language-configuration.json`)
  ports `clients/vscode/language-configuration.json`, keeping the
  sections the Visual Studio Language Configuration documentation
  defines (comments, brackets, autoclosing, surrounding, word pattern).
  The VS Code-only rules (folding markers, on-enter rules) stay out
  until the docs say the editor understands them.

Run after editing the shared sources:

    python3 clients/visualstudio/scripts/sync-assets.py
"""

import json
import pathlib
import plistlib

HERE = pathlib.Path(__file__).resolve().parents[1]  # clients/visualstudio
ROOT = HERE.parents[1]  # the repository root
GRAMMAR_SOURCE = ROOT / "clients" / "shared" / "epher.tmLanguage.json"
CONFIG_SOURCE = ROOT / "clients" / "vscode" / "language-configuration.json"

# The sections the Language Configuration documentation defines.
CONFIG_SECTIONS = (
    "comments",
    "brackets",
    "autoClosingPairs",
    "autoCloseBefore",
    "surroundingPairs",
    "wordPattern",
)

with GRAMMAR_SOURCE.open(encoding="utf-8") as f:
    grammar = json.load(f)

grammar["fileTypes"] = ["epher"]

grammar_target = HERE / "Grammars" / "epher.tmLanguage"
grammar_target.parent.mkdir(exist_ok=True)
with grammar_target.open("wb") as f:
    plistlib.dump(grammar, f)

with CONFIG_SOURCE.open(encoding="utf-8") as f:
    config = json.load(f)

kept = {key: config[key] for key in CONFIG_SECTIONS if key in config}

config_target = HERE / "epher-language-configuration.json"
with config_target.open("w", encoding="utf-8") as f:
    json.dump(kept, f, indent=2)
    f.write("\n")

print(f"wrote {grammar_target.relative_to(ROOT)} from {GRAMMAR_SOURCE.relative_to(ROOT)}")
print(f"wrote {config_target.relative_to(ROOT)} from {CONFIG_SOURCE.relative_to(ROOT)}")
